version: '3'

services:
  sma-query:
    image: sma-query:latest
    container_name: sma-query
    volumes:
      - /<docker>/config_measurements.json:/config_measurements.json
      - /<docker>/config_queries.json:/config_queries.json
    environment:
      - influx_ip=<192.168.1.3>
      - influx_port=<8086>
      - influx_db=<SMA>
      - influx_user=<user>
      - influx_pw=<pw>
      - sma_ip=<192.168.1.2>
      - sma_pw=<pw>
      - sma_mode=https
      - interval=15
      - write=1
      - TZ=Europe/Berlin
    logging:
      driver: "json-file"
      options:
        max-size: "5M"
        max-file: "10"
    restart: unless-stopped