version: '3'

services:
  sma-query:
    image: sma-query:latest
    container_name: sma-query
    environment:
      - influx_ip=192.168.1.3
      - influx_por=8086
      - influx_user=user
      - influx_pw=pw
      - sma_ip=192.168.1.2
      - sma_pw=pw
      - interval=15
    restart: unless-stopped