version: '3'

services:
  sma-query:
    image: sma-query:latest
    container_name: sma-query
    environment:
      - influx_ip=<192.168.1.3>
      - influx_por=<8086>
      - influx_user=<user>
      - influx_pw=<pw>
      - sma_ip=<192.168.1.2>
      - sma_pw=<pw>
      - sma_mode=https
      - interval=15
      logging:
        driver: "json-file"
        options:
          max-size: "500k"
          max-file: "5"
    restart: unless-stopped