{
 "title": "SMA Dashboard",
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DB_SMA", "label": "SMA Influx DB", "query": "influxdb" }
  ]
 },
 "panels": [
  {
   "title": "Last Month",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "kwatt", "label": "kilo Watt" }
   ],
   "targets": [
    {
     "alias": "Solar",
     "measurement": "totals_daily",
     "select": [
      [
       { "params": [ "solar_daily" ], "type": "field" },
       { "params": [ "/1000" ], "type": "math" }
      ]
     ],
     "tz": "Europe/Berlin"
    },
    {
     "alias": "Consumption",
     "measurement": "totals_daily",
     "select": [
      [
       { "params": [ "consumption_daily" ], "type": "field" },
       { "params": [ "/1000" ], "type": "math" }
      ]
     ],
     "tz": "Europe/Berlin"
    },
    {
     "alias": "Supply",
     "measurement": "totals_daily",
     "select": [
      [
       { "params": [ "einspeisung_daily" ], "type": "field" },
       { "params": [ "/1000" ], "type": "math" }
      ]
     ],
     "tz": "Europe/Berlin"
    },
    {
     "alias": "Bezug",
     "measurement": "totals_daily",
     "select": [
      [
       { "params": [ "bezug_daily" ], "type": "field" },
       { "params": [ "/1000" ], "type": "math" }
      ]
     ],
     "tz": "Europe/Berlin"
    }
   ]
  },
  {
   "title": "Solar Generation",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "actuals_5min",
     "select": [
      [
       { "params": [ "solar_5min" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/12/1000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Modul Current and Voltage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "Volt",
     "measurement": "dc",
     "select": [
      [
       { "params": [ "voltage_a" ], "type": "field" },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Current",
     "measurement": "dc",
     "select": [
      [
       { "params": [ "current_a" ], "type": "field" },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Solar",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "Solar",
     "measurement": "actuals",
     "select": [
      [
       { "params": [ "solar_act" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Einspeisung",
     "measurement": "actuals",
     "select": [
      [
       { "params": [ "einspeisung_act" ], "type": "field" }
      ]
     ]
    },
    { "target": "sun_altitude" }
   ]
  },
  {
   "title": "Solar Efficiency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "Solar DC",
     "measurement": "dc",
     "select": [
      [
       { "params": [ "power_a" ], "type": "field" }
      ]
     ],
     "tz": "Europe/Berlin"
    },
    {
     "alias": "Solar AC",
     "measurement": "ac",
     "select": [
      [
       { "params": [ "power" ], "type": "field" }
      ]
     ],
     "tz": "Europe/Berlin"
    }
   ]
  },
  {
   "title": "Consumption",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "Bezug",
     "measurement": "actuals",
     "select": [
      [
       { "params": [ "bezug_act" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Verbrauch",
     "measurement": "actuals",
     "select": [
      [
       { "params": [ "consumption_act" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Verbrauch P1",
     "measurement": "phases",
     "select": [
      [
       { "params": [ "consumption_1" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Verbrauch P2",
     "measurement": "phases",
     "select": [
      [
       { "params": [ "consumption_2" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Verbrauch P3",
     "measurement": "phases",
     "select": [
      [
       { "params": [ "consumption_3" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last Year",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "kwatt", "label": "kilo Watt" }
   ],
   "targets": [
    {
     "alias": "Solar",
     "measurement": "totals_daily",
     "select": [
      [
       { "params": [ "solar_daily" ], "type": "field" },
       { "params": [ "/1000" ], "type": "math" }
      ]
     ],
     "tz": "Europe/Berlin"
    },
    {
     "alias": "Consumption",
     "measurement": "totals_daily",
     "select": [
      [
       { "params": [ "consumption_daily" ], "type": "field" },
       { "params": [ "/1000" ], "type": "math" }
      ]
     ],
     "tz": "Europe/Berlin"
    },
    {
     "alias": "Supply",
     "measurement": "totals_daily",
     "select": [
      [
       { "params": [ "einspeisung_daily" ], "type": "field" },
       { "params": [ "/1000" ], "type": "math" }
      ]
     ],
     "tz": "Europe/Berlin"
    },
    {
     "alias": "Bezug",
     "measurement": "totals_daily",
     "select": [
      [
       { "params": [ "bezug_daily" ], "type": "field" },
       { "params": [ "/1000" ], "type": "math" }
      ]
     ],
     "tz": "Europe/Berlin"
    }
   ]
  }
 ]
}